name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Make sure build/ci work properly
        run: |
          pnpm all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test create app
        uses: ./
        with:
          host: "${{ secrets.CAPROVER_URL }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          app: test-app-from-gh-action
          action: create-app

      - name: Test delete app
        uses: ./
        with:
          host: "${{ secrets.CAPROVER_URL }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          app: test-app-from-gh-action
          action: delete-app
